package com.keakimleang.springbatchwebflux.payloads;

import lombok.*;

@Getter
public enum ErrorCode {
    AUTH("AUTH-401"),
    STATIC_RESOURCE_NOT_FOUND("RES-404-01"),
    RESOURCE_NOT_FOUND("RES-404-02"),
    INPUT_VALIDATION("VALID-400"),
    ACCESS_DENY_01("AUTH-403-01"),
    ACCESS_DENY_02("AUTH-403-02"),
    BUSINESS_RULE_VALIDATION("BIZ-VALID-422"),
    INTERNAL_SERVER_ERROR("INT-SERVER-500"),
    EXTERNAL_SERVICE_ERROR_4XX("EXT-SERVER-4XX"),
    EXTERNAL_SERVICE_ERROR_4X1("EXT-SERVER-401"),
    EXTERNAL_SERVICE_ERROR_4X3("EXT-SERVER-403"),
    EXTERNAL_SERVICE_ERROR_4X4("EXT-SERVER-404"),
    EXTERNAL_SERVICE_ERROR_5XX("EXT-SERVER-500"),
    EXTERNAL_SERVICE_ERROR_503_01("EXT-SERVER-503-01"),
    EXTERNAL_SERVICE_ERROR_503_02("EXT-SERVER-503-02"),
    FEIGN_SERVICE_ERROR("EXT-SERVER-FEIGN"),
    FEIGN_OPEN_STATE("EXT-SERVER-FEIGN-OPEN"),
    BATCH_JOB_ERROR("BATCH-JOB-500");

    private final String code;

    ErrorCode(final String code) {
        this.code = code;
    }
}
